### ISSUE TITLE
Wrong account is used to create a doc

### ISSUE THREAD

**Issue by tmandry** [dmihal/Google-Docs-Quick-Create#1]
I have two Chrome profiles, one with my personal email (@gmail.com) and one with my work email as the default Google account. (I'm signed into both accounts in each, though.)

I used this extension first in my personal profile, no problem. Then I installed on the work profile and tried to use it again, but it always creates the doc using my personal email account. I can't get it to use the work account. This is pretty odd considering that the work account is the default Google account.

**Comment by dmihal** [comment]
Based on http://webapps.stackexchange.com/questions/26304/url-to-create-a-new-google-document, it looks like the URLs to make new docs have been updated. I'll try updating them to see if that resolves your issue.

It also looks like different URLs might be required for Google Apps accounts, like `https://docs.google.com/a/your.domain.com/document/create`. In that case, adding Google Apps support will take more work...

**Comment by lsaewitz** [comment]
Has this been resolved? I'm having the same problem and can't seem to get the extension to use my work account instead of my personal gmail account.

**Comment by dmihal** [comment]
@tmandry @lsaewitz Sorry for the slow response. I've updated the extension to address these issues, the fix is available in v0.1.3. If your browser hasn't updated yet, you can force an update by following [these instructions](http://lifehacker.com/5805239/how-to-manually-update-your-chrome-extensions).

To enable support for your work account, right click the icon, select options, and enter the domain for your work account.

I plan on improving the interface, but I wanted to get the extension out there with the bug fixed.

Please let me know if you have any issues or other feedback!

**Comment by lsaewitz** [comment]
Thanks!!


_______

[image: Origin_Ventures.jpg] <http://originventures.com/>

Lindsay Saewitz

General Manager, Origin Ventures Network | Origin Ventures

o 312-324-3480 | m 847-987-3470 | lindsay@originventures.com

@OriginVentures <https://twitter.com/OriginVentures>

**Comment by lsaewitz** [comment]
Actually, still not sure how to get it working.

I've gotten to the part where you add your work domain:
[image: Inline image 1]

But can't seem to get it to save or work. I've added just the domain (@
originventures.com) and also my email, lindsay@originventures.com. Please
advise.


_______

[image: Origin_Ventures.jpg] <http://originventures.com/>

Lindsay Saewitz

General Manager, Origin Ventures Network | Origin Ventures

o 312-324-3480 | m 847-987-3470 | lindsay@originventures.com

@OriginVentures <https://twitter.com/OriginVentures>

On Thu, Oct 15, 2015 at 9:19 AM, Lindsay Saewitz <lindsay@originventures.com

**Comment by dmihal** [comment]
@lsaewitz The domain should just be `originventures.com`, without the @ sign.

My next update will disallow characters like @, hopefully making it a little more intuitive.

**Comment by lsaewitz** [comment]
Perfect! Thanks so much. super helpful.


_______

[image: Origin_Ventures.jpg] <http://originventures.com/>

Lindsay Saewitz

General Manager, Origin Ventures Network | Origin Ventures

o 312-324-3480 | m 847-987-3470 | lindsay@originventures.com

@OriginVentures <https://twitter.com/OriginVentures>

**Comment by dmihal** [comment]
@lsaewitz :smiley_cat:
